### ISSUE TITLE
vNext RC1 Breaking Changes

### ISSUE THREAD

**Issue by prom3theu5** [TheTree/branch#75]
Package Changes:
EntityFramework.SqlServer -> EntityFramework.MicrosoftSqlServer
Microsoft.Framework.Logging/.* -> Microsoft.Extensions.Logging/.*
Microsoft.Framework.Configuration/.* -> Microsoft.Extensions.Configuration/.*
using Microsoft.AspNet.Razor.Runtime.TagHelpers -> using Microsoft.AspNet.Razor.TagHelpers

TagHelper Changes:

Before

    public class CustomTagHelper : TagHelper
    {
        public override async Task ProcessAsync(TagHelperContext context, TagHelperOutput output)
        {
            await context.GetChildContentAsync();
        }
    }

After

    public class CustomTagHelper : TagHelper
    {
        public override async Task ProcessAsync(TagHelperContext context, TagHelperOutput output)
        {
            await output.GetChildContentAsync();
        }
    }

**Comment by 0xdeafcafe** [comment]
ah shit, rc1 came out. thanks man

**Comment by prom3theu5** [comment]
No worries man
Was just having a look through your solution.
Not touched on vNext myself yet - but you've certainly shown me a lot of its potential.

Love the built in DI

**Comment by 0xdeafcafe** [comment]
Yeah, the built in DI is amazing. Still no idea how to write tests for it though, haha.

**Comment by prom3theu5** [comment]
It is man :)
From what I've read, only xUnit testing works atm (unless that changed with RC1's release).
Brave New World with OOTB DI and Multiplatform hosting.

How is Azure's Document database treating you?
Faster than MongoDB for writes?
